---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: centos
    tag: latest
inputs:
  - name: ci-repo
  - name: version
  - name: pcc-demo-model
  - name: pcc-demo-function
outputs:
  - name: post-artifacts
run:
  path: /bin/bash
  args:
    - ci-repo/ci/.concourse/pcc/tasks/update-version.sh
