---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: centos
    tag: latest
inputs:
  - name: repo
  - name: version
  - name: artifact
outputs:
  - name: post-artifact
run:
  path: /bin/bash
  args:
    - repo/ci/tasks/update-version.sh
