---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: code-repo
  - name: ci-repo
  - name: version
    optional: true
outputs:
  - name: artifacts
run:
  path: /bin/bash
  args:
    - ci-repo/ci/.concourse/tasks/build.sh

caches:
  - path: gradle
  - path: maven

params:
  PROJECT_TYPE: 