---
# Spring Boot application properties that are applied when the "local" Spring profile is enabled with
#-Dspring.profiles.active=local
spring:
  profiles: local
  data:
    gemfire:
      security:
        username: pcc
        password: test

customer-order:
  service:
    name:
      base: customer-order-service
      suffix: 2019
      full: ${customer-order.service.name.base} + '-' + ${customer-order.service.name.suffix}

server:
  port: 8081